### ISSUE TITLE
Possible bug when using case_bootstrap() on lme-model

### ISSUE THREAD

**Issue by jRafi** [aloy/lmeresampler#1]
The case_bootstrap-function returns the error "could not find function cases.resamp" when I give it a lme-object, but not an nlme-object. Since the bootstrap-function worked on the same objects, I figured there could be a bug when using case_bootstrap on lme-objects.

For a reproducible example, see: https://github.com/jRafi/Shareworthy/blob/master/case_bootstrap.lmer.R

**Comment by aloy** [comment]
Thanks for catching this! I changed the way I called `.cases.resamp` for the lme4 package, but forgot to make the same change for the other function. I just pushed the fix.

**Comment by jRafi** [comment]
That was quick! Thanks for responding and thank you for a great package.

Best
Jonas Rafi


________________________________

**Comment by jedimacdonald** [comment]
Hi Adam, 

Following on from Jonas' comment, just wondering if any recent (i.e. since January 2022) changes have been made to way the lmeresampler bootstrap function works with lme objects for a cases bootstrap? I'm getting reasonable results for a lmer model object, but not for the equivalent lme model object. R code and a test dataset attached to illustrate. 

Cheers,
Jed
[Cases bootstrap with lme.zip](https://github.com/aloy/lmeresampler/files/9367730/Cases.bootstrap.with.lme.zip)
